Update README with archival message
strangelove-ventures/lens pull request #316
Opened 2023-05-22 01:53 UTC by vimystic

2023-05-22 04:10 UTC, agouin requested changes
Are we going to archive the repo or mark it as inactive? I thought we were going to keep the repo open for PRs but notify that it is no longer being actively developed by Strangelove

2023-05-22 04:10 UTC, agouin commented on README.md
> +The repository was divided into two main packages: `cmd`, which housed the `lens` command-line tool, and `client`, comprising foundational elements to develop Cosmos clients in Go.
This sentence is redundant to existing content in this file.

2023-05-22 04:10 UTC, agouin commented on README.md
> +It found utility in various scenarios like trading bots, server-side integrations, indexers, search engines, and transaction automation for farming applications.
This sentence is also redundant

2023-05-22 04:10 UTC, agouin commented on README.md
> +This repository is no longer active. For ongoing development or usage of Cosmos client libraries, please refer to the latest resources.
What latest resources?

2023-05-22 04:10 UTC, agouin commented on README.md
> +The "lens" repository, developed by Strangelove Ventures, is now archived. It served as a command-line tool and library to interact with Cosmos chains, supporting the core Cosmos-SDK modules.
```suggestion
The "lens" repository, developed by Strangelove, is now archived. It served as a command-line tool and library to interact with Cosmos chains, supporting the core Cosmos-SDK modules.
```

2023-05-22 04:10 UTC, agouin commented on README.md
> +The "lens" repository, developed by Strangelove Ventures, is now archived. It served as a command-line tool and library to interact with Cosmos chains, supporting the core Cosmos-SDK modules.
Second sentence here is redundant to lines 14-16

2023-05-22 19:11 UTC, vimystic commented
> Are we going to archive the repo or mark it as inactive? I thought we were going to keep the repo open for PRs but notify that it is no longer being actively developed by Strangelove

This is now resolved with an update.

2023-05-22 19:52 UTC, agouin commented on README.md
> +The "lens" repository, developed by Strangelove, is now inactive. It serves as a command-line tool and library to interact with Cosmos chains, supporting the core Cosmos-SDK modules.This repo will be
```suggestion
This repository is now inactive. It will be kept open (non-archived) but will no longer be actively developed by Strangelove.
```

2023-06-23 07:12 UTC, agouin approved these changes

2023-06-23 07:12 UTC, merged